### PR TITLE
Add  media queries to make the site responsive

### PR DESCRIPTION
**Pull request by yusufhawwah**
This pull request adds the CSS code to transform the travel website from a mobile-only travel website to a fully responsive website that adapts to all screen sizes. The layout includes:
Header with navigation links,
Navigation bar,
Cards showcasing travel destinations,
Footer with contact information and links.
Note: The initial code did not clone correctly to Git and showed as untracked files. To resolve this, I copied all code, deleted the original repository, created a new one, and pasted the code here. This reset explains the limited number of commits in this repository.

### CODE REVIEW

**Review by Xfarouq — CHANGES_REQUESTED** [review]
Hi @yusufhawwah 

Good job so far!
You still need to work on some issues to get your project approved, but you are almost there!

<div style="text-align:center;">
    Remote Collaboration
</div>

### To Highlight 💯
- **Clean code** 👍
- **Good use of Gitflow** 👍
- **Implemented some project requirements** 👍

### Required Changes ♻️

- Always add readme before submitting your projects and make sure you deploy your links well

- kindly consider having the app's name on the splash screen as requested in the project requirement or as given on the design

### Optional Suggestions
Every comment with the `[OPTIONAL]` prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding! 👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.  
Please, remember to tag me in your question so I can receive the notification._

**Review by Xfarouq — CHANGES_REQUESTED** [review]
Hi @yusufhawwah 

Good job so far!
You still need to work on some issues to get your project approved, but you are almost there!

<div style="text-align:center;">
    Remote Collaboration
</div>

### To Highlight 💯
- **Clean code** 👍
- **Good use of Gitflow** 👍
- **Implemented some project requirements** 👍

### Required Changes ♻️

-Please deploy your website on render well so that it will be working when clicked
- If your having problem with it please reach out

### Optional Suggestions
Every comment with the `[OPTIONAL]` prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding! 👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.  
Please, remember to tag me in your question so I can receive the notification._

**Comment by yusufhawwah** [comment]
I have changed the directory and the site is working. since I have made the site responsive can I Submit the pull request as the 3rd project that is responsive instead of mobile only? @Xfarouq

**Comment by Xfarouq** [comment]
Yes you may proceed

**Review by Devsalmasaeed — APPROVED** [review]
Hi @yusufhawwah ,

Your project is complete! There is nothing else to say other than... it's time to merge it!!!
Congratulations! 🎉

<div style="text-align:center;">
    Remote Collaboration
</div>

### Highlights
- ✅ **Professional Readme**
- ✅ **Good use of Gitflow**
- ✅ **UI looks like the Figma design**
- ✅ **Good use of HTML semantics**
- ✅ **Professional commit messages**
- ✅ **Professional PR title**
- ✅ **Professional PR description**

### Optional Suggestions
Every comment with the `[OPTIONAL]` prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding! 👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.  
Please, remember to tag me in your question so I can receive the notification._

**Pull request merged**
